ingress:
  enabled: true
  className: "nginx"
  annotations: 
      ingress.kubernetes.io/ssl-redirect: "false"
      cert-manager.io/cluster-issuer: letsencrypt-uat
      acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: uat-app.theilyas.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: chart-example-tls
     hosts:
       - uat-app.theilyas.com